import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./(components)/navbar";
import { Toaster } from "@/components/ui/toaster";
import { TooltipProvider } from "@/components/ui/tooltip";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Narratioverse",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TooltipProvider>
          <Navbar />
          <div>{children}</div>
          <Toaster />
        </TooltipProvider>
      </body>
    </html>
  );
}
